AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Storage resources

Parameters:
  DocumentStoreBucketName:
    Type: String
  WebStoreBucketName:
    Type: String

Resources:
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DocumentStoreBucketName
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD, PUT, POST, DELETE]
            AllowedOrigins: ['*']
            ExposedHeaders: [ETag]
            MaxAge: 3000

  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebStoreBucketName
      WebsiteConfiguration:
        IndexDocument: index.html

  DocsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Documents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: file
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: file
          KeyType: RANGE

  GeneralTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: General
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  DocsTableName:
    Value: !Ref DocsTable
  GeneralTableName:
    Value: !Ref GeneralTable
  DocumentStoreBucketName:
    Value: !Ref DocumentBucket
  WebStoreBucketName:
    Value: !Ref WebBucket 