AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FCJ DMS - Unified SAM Template

Parameters:
  DocumentStoreBucketName:
    Type: String
    Default: fcjdmsstore
  WebStoreBucketName:
    Type: String
    Default: fcjdmswebstore

# --- Auth Resources ---
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: fcj-dms-userpool
      AutoVerifiedAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: fcj-dms-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: fcj-dms-identitypool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

# --- Storage Resources ---
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DocumentStoreBucketName
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD, PUT, POST, DELETE]
            AllowedOrigins: ['*']
            ExposedHeaders: [ETag]
            MaxAge: 3000

  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebStoreBucketName
      WebsiteConfiguration:
        IndexDocument: index.html

  DocsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Documents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: file
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: file
          KeyType: RANGE

  GeneralTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: General
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

# --- API & Lambda Functions ---
  DocsList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/list_docs/
      Handler: list_docs.lambda_handler
      Runtime: python3.9
      FunctionName: list_docs
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DocsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref DocsTable
      Events:
        ListDocs:
          Type: Api
          Properties:
            Path: /docs/{id}
            Method: get
            RestApiId: !Ref Api

  DocsUpload:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/upload_doc/
      Handler: upload_doc.lambda_handler
      Runtime: python3.9
      FunctionName: upload_doc
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DocsTable
        - S3CrudPolicy:
            BucketName: !Ref DocumentBucket
      Environment:
        Variables:
          TABLE_NAME: !Ref DocsTable
          BUCKET_NAME: !Ref DocumentBucket
      Events:
        UploadDocs:
          Type: Api
          Properties:
            Path: /docs
            Method: post
            RestApiId: !Ref Api

  DocsDelete:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/delete_doc/
      Handler: delete_doc.lambda_handler
      Runtime: python3.9
      FunctionName: delete_doc
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocsTable
        - S3CrudPolicy:
            BucketName: !Ref DocumentBucket
      Environment:
        Variables:
          TABLE_NAME: !Ref DocsTable
          BUCKET_NAME: !Ref DocumentBucket
      Events:
        DeleteDoc:
          Type: Api
          Properties:
            Path: /docs/{id}
            Method: delete
            RestApiId: !Ref Api

  GeneralInforUpload:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/upload_general_infor/
      Handler: upload_general_infor.lambda_handler
      Runtime: python3.9
      FunctionName: upload_general_infor
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GeneralTable
      Environment:
        Variables:
          TABLE_NAME: !Ref GeneralTable
      Events:
        UploadGeneral:
          Type: Api
          Properties:
            Path: /docs/{id}/gen
            Method: post
            RestApiId: !Ref Api

  GeneralInforGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/get_general_infor/
      Handler: get_general_infor.lambda_handler
      Runtime: python3.9
      FunctionName: get_general_infor
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GeneralTable
      Environment:
        Variables:
          TABLE_NAME: !Ref GeneralTable
      Events:
        GetGeneral:
          Type: Api
          Properties:
            Path: /docs/{id}/gen
            Method: get
            RestApiId: !Ref Api

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev"
  WebBucket:
    Description: "Web S3 Bucket"
    Value: !Ref WebBucket
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool 